import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ZustandProvider } from "@/providers/zustand-provider";
import Footer from "../_components/Footer";
import Aside from "../_components/Aside";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen w-screen flex flex-col items-center justify-center bg-slate-800`}
        suppressHydrationWarning
      >
        <ZustandProvider>
          <main className="w-screen flex-1 flex flex-col items-center justify-center">
            <div className="w-1/2 h-[600px] flex flex-col justify-center items-center bg-gradient-to-b from-pink-100 to-pink-200">
              <div className="w-full h-full flex">
                <Aside />
                {children}
              </div>
              <div className="w-full h-16 flex justify-center items-center gap-4 bg-[#ff9bac]">
                <Footer />
              </div>
            </div>
          </main>
          <footer className="w-screen px-10 h-10 flex items-center justify-end">
            k@toDev
          </footer>
        </ZustandProvider>
      </body>
    </html>
  );
}
