import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ZustandProvider } from "@/providers/zustand-provider";
import Aside from "../_components/Aside";
import TimeLine from "../_components/Timeline";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen w-screen flex flex-col items-center justify-center bg-pink-100`}
        suppressHydrationWarning
      >
        <ZustandProvider>
          <main className="w-screen flex-1 flex flex-col items-center justify-center">
            <div className="w-2/3 h-[600px] flex flex-col justify-center items-center bg-gradient-to-b from-pink-100 via-[#FADBE0] to-[#ffc0cb] shadow-[6px_6px_10px_3px_rgba(0,0,0,0.15)] overflow-hidden">
              <div className="w-full h-full flex">
                <Aside />
                <div className="w-2/3 flex flex-col">
                  {children}
                  <TimeLine />
                </div>
              </div>
            </div>
          </main>
          <footer className="w-screen px-10 h-10 flex items-center justify-end">
            k@toDev
          </footer>
        </ZustandProvider>
      </body>
    </html>
  );
}
