import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";
import { ZustandProvider } from "@/providers/zustand-provider";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="es" suppressHydrationWarning>
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased w-screen flex flex-col items-center justify-center bg-pink-100`}
                suppressHydrationWarning
            >
                <div
                    className="fixed inset-0 z-[-10]"
                    style={{
                        background: `linear-gradient(270deg, #FFECB3 0%, #FFE0B2 20%, #FFCDD2 40%, #F8BBD9 60%, #E1BEE7 80%, #D1C4E9 100%)`,
                    }}
                ></div>

                <ZustandProvider>
                    <main className="w-screen flex-1 flex flex-col items-center justify-center my-6">
                        {children}
                    </main>
                </ZustandProvider>
            </body>
        </html>
    );
}
